### ISSUE TITLE
Errors in the implementation of user messages

### ISSUE THREAD

**Issue by JulieVanHoudenhove** [JulieVanHoudenhove/GL02_MACHINE_A24#1]
Change the different error messages : 

- [x] Test 1.5.1
- [x] Test 1.5.2
- [x] Test 1.3.1
- [x] Test 2.4.1

**Comment by lcgrn** [comment]
# Titre : Erreurs dans l'implémentation des messages affichés à l'utilisateur 

**Description du porblème** : Les messages, d'erreurs ou de réussite d'une action, affichés à l'utilisateur sur l'interface de commande ne sont pas ceux qui sont spécifiés dans le cahier des charges. 

## Reproduire les problèmes liés aux messages  

### **a) Génération d’un fichier GIFT avec un nombre de questions non valide** : 
- Tapez 1 sur l'interface de commande, puis suivez les instructions pour ajouter une question à un examen 
- Tapez 2 sur l'interface de commande pour créer un examen 

**Résultat attendu :** Un message indiquant _"Votre examen ne contient pas entre 15 et 20 questions, veuillez corriger cela"_

**Résultat obtenu :** _"Votre examen doit contenir entre 15 et 20 questions. Actuellement : 1"_
![Image 22-12-2024 à 18 18](https://github.com/user-attachments/assets/17eed5ac-6a53-4fa2-837b-f702a999082b)
_ref test 1.5.1_

### **b) Détection de doublons dans les questions sélectionnées pour créer l'examen**: 
- Tapez 1 sur l'interface de commande, puis suivez les instructions pour ajouter une question à un examen 
- Refaites la même étape que précédemment en ajoutant la même question 
- Ajoutez des questions à l'examen pour en avoir entre 15 et 20, sinon vous ne pourrez pas généré de fichier
- Tapez 2 sur l'interface de commande pour créer un examen 

**Résultat attendu** : Le message suivant s'affiche : _Au moins une question est en double, veuillez vérifier vos données._

**Résultat obtenu** : Le message suivant s'affiche : _Doublon détecté : EM U4 p33 Review 4.6 for the first time_

![Image 22-12-2024 à 18 25](https://github.com/user-attachments/assets/5d914364-d744-45c9-af51-b47c247ce32e)
_ref test 1.5.2_

### c) Génération d'un fichier GIFT valide : 
- Ajoutez des questions à l'examen ( pas de questions en doubles et un nombre de question compris entre 15 et 20)
- Tapez 2 sur l'interface de commande pour créer l'examen

Résultat attendu : Un message indiquant à l'utilisateur : "_Votre fichier a été généré avec succès”_
Résultat obtenu : _Examen GIFT créé avec succès : ./examens/exam2.gift_

![Image 22-12-2024 à 18 36](https://github.com/user-attachments/assets/925ba131-a299-482a-819c-3b419f2e49ad)

_ref test 1.3.1_

### **d) Génération d’un fichier VCard avec des informations incomplètes**
- Tapez 3 pour accéder à la partie "s'identifier" du logiciel 
- Rentrez une donnée invalide 

Résultat attendu : Un message indiquant à l'utilisateur "_Veuillez compléter les informations manquantes."_
Résultat obtenu : Des messages variant en fonction des données qui ne sont pas valides par exemple : _Le prénom ne peut pas être vide.; L'email fourni n'est pas valide._

![Image 22-12-2024 à 18 44](https://github.com/user-attachments/assets/2b334889-fdf1-4c98-acdb-7a9852f00fe1)
_ref test 2.4.1_



**Priorité** : Faible 
L'affichage des messages n'empêche en aucun cas l'utilisation du logiciel et ne nuit pas aux fonctionnalités de celui - ci 

**Informations techniques :**
Machine : Ordinateur personnel
OS : MacOS Sonoma 14.6.1
Version Node.js : v21.7.1
Outils associés : Fichiers GIFT et VCard de test fournis
Groupe de test : Lucie Guérin, Julie Van Houdenhove, Théo Torreilles

**Comment by lcgrn** [comment]
## Modifications réalisées 

### **a) Génération d’un fichier GIFT avec un nombre de questions non valide** 
Modification du message en laissant le nombre de question qui s'affiche car même si cela n'était pas spécifié dans le message du cahier des charges cela donne une très bonne indication à l'utilisateur. Grâce à cela il sait combien de question il lui reste à ajouter à son examen pour que celui-ci soit conforme. 

```
console.log(
      `\nVotre examen ne contient pas entre 15 et 20 questions, veuillez corriger cela. Actuellement : ${questionsSelectionnees.length}`,
    );
```

### b) Détection de doublons dans les questions sélectionnées pour créer l'examen
Dans la fonction vérifierExamen, partie vérification des doublons, j'ai modifié le message de la manière suivante : 
```
      console.log(`\nAu moins une question est en double, veuillez vérifier vos données. Doublon détecté: ${question.titre}`);
```

J'ai laissé la deuxième partie du message car cela permet à l'utilisateur de savoir quelle question est en double dans son examen. 


### c) Génération d'un fichier GIFT valide 
Dans la fonction pour sauvegarder l'examen du fichier GIFT, j'ai apporté la modification suivante au code : 

```
 console.log(`\nVotre fichier a été généré avec succès : ${cheminComplet}`);
```
Même si cela n'était pas indiqué dans le cahier des charges, j'ai laissé l'indication sur le chemin du fichier. 


### d) Génération d’un fichier VCard avec des informations incomplètes

Dans les sous-fonctions permettant de remplir les données pour générer un fichier VCard j'ai modifié le message pour chacune des informations demandées lorsque l'utilisateur ne rentre pas les bonnes données. 

Par exemple : 
```
      console.log("Le nom ne peut pas être vide. Veuillez compléter les informations manquantes.");
```
```
console.log(
          "L'adresse fournie n'est pas valide. Le format attendu est : rue;code postal;ville;pays. \n Veuillez compléter les informations manquantes.",
        );
```
```
      console.log("Le numéro de bureau ne peut pas être vide. \n Veuillez compléter les informations manquantes.");
```
