### ISSUE TITLE
No warning for incomplete answers during exam simulation

### ISSUE THREAD

**Issue by JulieVanHoudenhove** [JulieVanHoudenhove/GL02_MACHINE_A24#11]
The system considers unanswered questions as incorrect without warning or allowing the user to revisit them.

**Reference**
Test 3.6.1

**Comment by lcgrn** [comment]
### Titre: Aucun message d'avertissent et de possibilité de modification en cas de réponses incomplètes lors de la simulation de la passation d'un examen

**Description du problème :** Lors de la simulation de la passation d'un examen, si l'utilisateur ne répond pas à une question, la réponse est automatiquement considérée comme fausse et il est impossible de revenir dessus. Aucun message n'indique que les réponses sont incomplètes et il n'est pas possible de revenir sur une question qui n'est pas compléte. 

**Étapes pour reproduire le problème :**
- Taper 4 sur l'interface de commande pour simuler la passation d'un examen 
- Entrer le chemin du fichier d'examen à passer. _Par exemple, ./examens/exam1.gift_
- Ne pas répondre à la question 
- Constater que le résultat indique : Mauvaise réponse et passe à la question suivante

**Comportement attendu :** 
⚠️Avertissement : Avant de soumettre, le système doit afficher un message :
_"Attention, vous n’avez pas répondu à toutes les questions, voulez-vous confirmer vos réponses ?"_
✅Options utilisateurs :
1. Oui : L’utilisateur valide les réponses et passe à la génération du bilan, avec une distinction entre questions non répondues et réponses incorrectes.
2. Non : L’utilisateur retourne sur les questions non répondues pour compléter ses réponses avant soumission.

**Résultat observé :** 
- Aucun message d’avertissement n’est affiché.
- Les réponses non fournies sont directement considérées comme incorrectes.
- L’utilisateur n’a pas la possibilité de revenir sur les questions non répondues avant la validation.

![Image 22-12-2024 à 15 34](https://github.com/user-attachments/assets/4adb0a76-e04d-4b8b-829d-4fde688c34f7)


**Priorité** : Haute
Impact sur la fiabilité des tests : les réponses non complétées ne sont pas distinguées des réponses incorrectes, ce qui fausse aussi la simulation. 

**Référence** : test 3.6.1

**Informations techniques :**
Machine : Ordinateur personnel
OS : MacOS Sonoma 14.6.1
Version Node.js : v21.7.1
Outils associés : Fichiers GIFT et VCard de test fournis
Groupe de test : Lucie Guérin, Julie Van Houdenhove, Théo Torreilles

**Comment by lcgrn** [comment]
### Changements apportés 

**Gestion des réponses vides**

- Si l'utilisateur laisse une réponse vide, un avertissement est affiché :

`console.log("\n⚠️ Vous n'avez pas répondu à cette question.");`

- Confirmation pour les réponses non fournies :
L'utilisateur doit confirmer son choix de ne pas répondre :
`rl.question("Confirmez-vous que vous ne souhaitez pas répondre à cette question ? (Oui/Non) : ", (confirmation) => { ... });
`

- Reprise ou continuation du test : Si l'utilisateur choisit "non", la question est reposée. Sinon, la réponse est enregistrée comme incorrecte, et on passe à la suivante :

```
if (confirmation.toLowerCase() === "non") {
  console.log("Veuillez entrer votre réponse.");
  return askQuestion(); // Relancer la question
}
console.log("Réponse non fournie, enregistrée comme incorrecte)
```

![Image 22-12-2024 à 16 06](https://github.com/user-attachments/assets/deb7de73-36e3-4ba5-bac9-57c5552deb7e)


Pistes d'améliorations possibles : 

- On pourrait envisager de différencier une réponse vide d'une mauvaise réponse. 
- Au lieu de donner la réponse à chaque que l'on répond à une question, l'utilisateur passe l'examen en entier puis lorsqu'il soumet ses réponses, la correction est donnée.
