### ISSUE TITLE
No limit on the number of files for exam profile comparison

### ISSUE THREAD

**Issue by JulieVanHoudenhove** [JulieVanHoudenhove/GL02_MACHINE_A24#12]
Users can compare unlimited number of exam profiles, whereas the specification states it should be limited to 1-3 files.

**Reference**
Test 5.8.1

**Comment by lcgrn** [comment]
### Titre: [Bug] Limitation incorrecte du nombre d’examens comparés

**Description du problème** : Lors de la comparaison des profils d'examens, l'utilisateur peut actuellement ajouter un nombre illimité de fichiers de la banque de questions. Cependant, selon le cahier des charges, l'utilisateur doit pouvoir sélectionner entre 1 et 3 fichiers maximum.

**Étapes pour reproduire le problème :**
- Aller à la page de comparaison des examens (en tapant 5).
- Sélectionner le profil d'un examen à comparer. Il faut qu'un examen au moins ai été crée au préalable. 
- Entrer les chemins des fichiers GIFT de référence (séparés par des virgules) que l'on souhaite comparer. _Par exemple : examens/examen.gift, examens/examen.gift, examens/examen.gift, examens/examen.gift,_
- Observer que le système permet d'ajouter un nombre illimité de fichiers.

**Comportement attendu :** Le système doit limiter le nombre de fichiers de la banque de questions sélectionnables à un maximum de 3. Si l'utilisateur tente d'ajouter plus de 3 fichiers, un message d'erreur doit s'afficher indiquant : "Vous ne pouvez sélectionner que jusqu'à 3 fichiers."

**Résultat observé :** Aucune limitation n’est appliquée, l’utilisateur peut ajouter un nombre illimité d’examens à comparer.

![Image 22-12-2024 à 14 54](https://github.com/user-attachments/assets/fcb1ddb5-3c5e-4f62-90b9-d9acd5a2576b)


**Priorité :** Haute 
_Cette fonctionnalité est essentielle pour la conformité avec les exigences et pour éviter des problèmes de performance ou d’expérience utilisateur. Sinon, le système risque la surcharge._ 

**Référence** : test 5.8.1

**Informations techniques :**
- Machine : Ordinateur personnel
- OS : MacOS Sonoma 14.6.1
- Version Node.js :  v21.7.1
- Outils associés : Fichiers GIFT et VCard de test fournis
- Groupe de test : Lucie Guérin, Julie Van Houdenhove, Théo Torreilles

**Comment by lcgrn** [comment]
### Changements réalisés : 

Ajout d’une limite sur le nombre de fichiers GIFT :
```
if (fichiersPaths.length > 3) {
  console.log("\nErreur : Vous ne pouvez comparer qu'un maximum de 3 fichiers.");
  return comparerProfilExamen(rl, callbackMenu); // Relancer la sélection en cas d'erreur
}
```
La vérification se fait juste après avoir extrait les chemins des fichiers GIFT.
Par ailleurs, si l’utilisateur dépasse la limite de 3 fichiers, un message d’erreur est affiché, et la fonction relance la sélection des fichiers.


![Image 22-12-2024 à 15 07](https://github.com/user-attachments/assets/30921675-bd1d-41b5-8d7a-f3e8d71309e8)
